# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/
name: uv lock update

on:
  push:
    branches:
    - renovate/**
    paths:
    - .github/workflows/uv-update.yml
  schedule:
  - cron: 30 6 * * 0
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yarn-update:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WEBLATE_CI_TOKEN }}

    - name: Lockfile maintenance
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      run: uv lock --upgrade --no-sourc

    - run: uv sync --all-extras --no-sources

    - name: Update current branch
      if: github.ref != 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore(deps): update lockfile'

    - name: Create Pull Request
      id: cpr
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@v7
      with:
        branch: create-pull-request/yarn-update
        title: 'chore(deps): update lockfile'
        commit-message: 'chore(deps): update lockfile'

        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        labels: |
          dependencies

    - name: Enable Pull Request Automerge
      if: github.ref == 'refs/heads/main' && steps.cpr.outputs.pull-request-operation != 'none'
      run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.WEBLATE_CI_TOKEN }}
